// Generated by CoffeeScript 1.9.3
(function() {
  var INIT_RATING, INIT_VOL, calc, update;

  update = require('./update');

  INIT_RATING = 1000;

  INIT_VOL = 400;

  calc = function(results, num) {
    var ARank, cnt, contest, ele, form, i, id, j, k, l, len, m, rating, ref, ref1, res, vol;
    if (num == null) {
      num = 50;
    }
    rating = (function() {
      var k, ref, results1;
      results1 = [];
      for (i = k = 0, ref = num; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
        results1.push(INIT_RATING);
      }
      return results1;
    })();
    vol = (function() {
      var k, ref, results1;
      results1 = [];
      for (i = k = 0, ref = num; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
        results1.push(INIT_VOL);
      }
      return results1;
    })();
    cnt = (function() {
      var k, ref, results1;
      results1 = [];
      for (i = k = 0, ref = num; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
        results1.push(0);
      }
      return results1;
    })();
    for (j = k = 0, ref = results.length; 0 <= ref ? k < ref : k > ref; j = 0 <= ref ? ++k : --k) {
      contest = results[j];
      form = [];
      for (l = 0, len = contest.length; l < len; l++) {
        id = contest[l];
        if (id >= num) {
          console.log("There is an invalid id in contest[" + j + "]. ");
          return [];
        }
        form.push({
          rating: rating[id],
          vol: vol[id],
          id: id
        });
      }
      for (i = m = 0, ref1 = form.length; 0 <= ref1 ? m < ref1 : m > ref1; i = 0 <= ref1 ? ++m : --m) {
        ++cnt[form[i].id];
        ARank = i + 1;
        res = update(ARank, form, cnt[form[i].id]);
        ele = form[i];
        rating[ele.id] = res.newRating;
        vol[ele.id] = res.newVol;
      }
    }
    return rating;
  };

  module.exports = calc;

}).call(this);

//# sourceMappingURL=calc.js.map
