// Generated by CoffeeScript 1.9.3
(function() {
  var build, calc;

  calc = require('./calc');

  build = function(contests, teamName) {
    var ele, i, j, len, r, rating, res;
    rating = calc(contests, teamName.length);
    res = [];
    for (i = j = 0, len = rating.length; j < len; i = ++j) {
      r = rating[i];
      ele = {
        rating: r,
        teamname: teamName[i]
      };
      res.push(ele);
    }
    res.sort(function(a, b) {
      if (a.rating < b.rating) {
        return 1;
      }
      return -1;
    });
    return res;
  };

  module.exports = build;

}).call(this);

//# sourceMappingURL=main.js.map
